# 1. URL ???? ??????. localhost ? ???? ?????????, 5432 ? ??????????? ???? Postgres.
# ecommerce_db ? ??? ??? ????, ??????? ???? ????? ??????? ? Postgres.
spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db

# 2. ???? ?????? ??? ????? ? PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=21091994

# 3. ??????? (??????????-??????????)
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. ????? Hibernate:
# update ????????, ??? Spring ??? ??????? ??????? ??? ??????? ??, ???? ?? ???????? ????? ???? ? Java-???.
spring.jpa.hibernate.ddl-auto=update

# 5. ????? ? ??????? ??????, ????? SQL-??????? Spring ?????????? ? ???? (??????? ??? ????????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true